### PR TITLE
fix sponsorCard style & img issue which mentioned in #72

### PR DESCRIPTION
**Pull request by alice6373**
## Types of Changes

**Thanks for sending a pull request! Please fill in the following content to let us know better about this change.**
Please put an `x` in the box that applies.

- [X] **Bugfix**
- [ ] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Other (please describe)**

## Related issue
#72

## Description
1.  Fix sponsor card tag styles : text color use #FFFFFF
2. Add diamond logo in sponsor card tag
3. Add pycon-snake icon in index sponsor region

## Screenshot
Desktop
_screen size : 1440 * 900_

<1 & 2> 
image
<3>
image

Mobile ( hide the tag & snake-with-py image in mobile view )
_iphone 5,  screen size : 320 * 568_

<1&2>
image

<3>
image

## Reference
1. [.hidden does not work with flex #345 in tailwindcss](https://github.com/tailwindlabs/tailwindcss/issues/345)
2. [Window Resizer chrome extension](https://chrome.google.com/webstore/detail/window-resizer/kkelicaakdanhinjdeammmilcgefonfh)
image

### CODE REVIEW

**Review by mattwang44 — CHANGES_REQUESTED** [review]
2 svg files used in this PR are not checkin

**Comment by alice6373** [comment]
> 2 svg files used in this PR are not checkin

Sorry and thanks for your reminder. I have checked in 2 svg files in this PR.

**Comment by mattwang44** [comment]
After the discussion with the designer, we believe we can hide the tag & `snake-with-py` image in mobile view.

<details>
<summary> problematic mobile view layout </summary>

image
image

</details>

**Comment by alice6373** [comment]
> After the discussion with the designer, we believe we can hide the tag & `snake-with-py` image in mobile view.
> 
> problematic mobile view layout
> image
> image

Thanks for your review and test. I have fixed sponsorCard mobile view.

**Review by mattwang44 — APPROVED** [review]
LGTM

**Pull request merged**
